tap "homebrew/bundle"

brew "mas"

mas "Xcode", id: 497799835

brew "nix"
brew "direnv"

brew "git"
brew "gh"

cask "android-studio"
cask "intellij-idea-ce"
cask "visual-studio-code"

# 必要になったタイミングで個別に追加してください
# cask "iterm2"
# cask "ghostty"
# cask "rectangle"
# cask "raycast"
